pdo:
  host: localhost
  dbname: kinaf
  user: root
  pass: ~
  driver: mysql
layout:
  name: default
cache:
  enabled: false
i18n:
  locales:
    en_US.utf8: 
      name: English
      date_format: m/d/Y
    fr_FR.utf8: 
      name: Français
      date_format: d/m/Y
  default: en_US.utf8
